# Generated by Django 5.1.2 on 2024-10-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('code_exp', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=510, null=True)),
                ('address', models.CharField(blank=True, max_length=510, null=True)),
                ('started', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField(blank=True, default=0, null=True)),
                ('lng', models.FloatField(blank=True, default=0, null=True)),
                ('archived', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'project',
                'managed': False,
            },
        ),
    ]
