# Generated by Django 5.1.2 on 2024-10-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'notification_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('txt', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'notification_template',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.IntegerField(blank=True, null=True)),
                ('txt', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'user_notification_option',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_notification', models.IntegerField(default=1)),
                ('push_notification', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'user_notification_setting',
                'managed': False,
            },
        ),
    ]
